[package]
name = "lrs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
trpl = "0.2.0"

hello_macro = { path = "hello_macro" }
hello_macro_derive = { path = "hello_macro/hello_macro_derive" }
